name: pqshield_mobile_app
description: "PQShield - Quantum-Resistant Security Platform for Mobile"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # ML & Security
  tflite_flutter: ^0.10.4
  crypto: ^3.0.3
  pointycastle: ^3.7.3

  # UI/UX
  cupertino_icons: ^1.0.6
  animations: ^2.0.11
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  lottie: ^3.1.0
  rive: ^0.13.1

  # Background Processing
  workmanager: ^0.5.2
  flutter_local_notifications: ^17.1.2
  flutter_background_service: ^5.0.5

  # Networking
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3

  # Storage
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3

  # Device Features
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  battery_plus: ^6.0.1
  network_info_plus: ^5.0.3

  # Charts & Visualization
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^25.2.7

  # Utils
  intl: ^0.19.0
  uuid: ^4.4.0
  logger: ^2.3.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0

  # Firebase Integration
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_messaging: ^14.9.2
  firebase_analytics: ^10.10.5

  # Biometrics & Security
  local_auth: ^2.1.8
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/
    - assets/images/
    - assets/animations/
    - assets/lottie/
    - assets/rive/
    - assets/icons/

  fonts:
    - family: PQShield
      fonts:
        - asset: assets/fonts/PQShield-Regular.ttf
        - asset: assets/fonts/PQShield-Bold.ttf
          weight: 700
        - asset: assets/fonts/PQShield-Light.ttf
          weight: 300

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/pqshield_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/pqshield_icon.png"
    background_color: "#0D47A1"
    theme_color: "#0D47A1"
  windows:
    generate: true
    image_path: "assets/icons/pqshield_icon.png"
    icon_size: 48
